name: Kafka Docker Push

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: kafka
  DOCKER_USERNAME: mooseconsulting

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Kafka.dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$DOCKER_USERNAME/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
